var mb=document.getElementById('mb'),mn=document.getElementById('menu');
mb.onclick=function(){var o=mn.classList.toggle('open');mb.setAttribute('aria-expanded',o)};
mn.onclick=function(){mn.classList.remove('open')};
var lb=document.getElementById('lb'),ci=document.getElementById('ci');
ci.onclick=function(){lb.firstChild.src=ci.src;lb.classList.add('on')};
ci.onkeydown=function(e){if(e.key==='Enter')ci.onclick()};
lb.onclick=function(){lb.classList.remove('on')};
document.getElementById('f').onsubmit=function(e){e.preventDefault();
var b='Name: '+n.value+'\nEmail: '+document.getElementById('e').value+'\n\n'+m.value;
location.href='mailto:MuskanAslam6969@gmail.com?subject='+encodeURIComponent(s.value)+'&body='+encodeURIComponent(b)};
var io=new IntersectionObserver(function(a){a.forEach(function(x){if(x.isIntersecting)x.target.classList.add('in')})},{threshold:.08});
document.querySelectorAll('.rv').forEach(function(x){io.observe(x)});
